[package]
name = "svg"
version = "0.1.0"
authors = ["wangrl2016 <wangrl2016@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.4.0"
usvg = "0.14.0"
log = "0.4.14"
tiny-skia = "0.5.1"
